"""Constants."""

KEY_MAP = {
    "anbudsdag": "Anbudsdag",
    "likviddag": "Likviddag",
    "forfallodag": "Forfallodag",
    "rantesats": "Rantesats",
    "rantesats_": "Rantesats",
    "erbjuden_volym_sek_md": "Erbjuden_volym",
    "erbjuden_volym_sek_mdr": "Erbjuden_volym",
    "totalt_budbelopp_sek_md": "Totalt_budbelopp",
    "totalt_budbelopp_sek_mdr": "Totalt_budbelopp",
    "tilldelad_volym_sek_md": "Tilldelad_volym",
    "tilldelad_volym_sek_mdr": "Tilldelad_volym",
    "antal_bud": "Antal_bud",
    "tilldelningsprocent": "Tilldelningsprocent",
    "tilldelningsprocent_": "Tilldelningsprocent",
    "auction_date": "Anbudsdag",
    "start_date": "Likviddag",
    "maturity_date": "Forfallodag",
    "interest_rate": "Rantesats",
    "interest_rate_": "Rantesats",
    "offered_volume_sek_bn": "Erbjuden_volym",
    "total_bid_amount_sek_bn": "Totalt_budbelopp",
    "accepted_volume_sek_bn": "Tilldelad_volym",
    "number_of_bids": "Antal_bud",
    "percentage_allotted": "Tilldelningsprocent",
    "percentage_allotted_": "Tilldelningsprocent",
    "percentage_alloted": "Tilldelningsprocent",
    "percentage_alloted_": "Tilldelningsprocent",
    "fixed_rate": "Rantesats",
    "nominal_amount_offered": "Erbjuden_volym",
    "total_bid_amount": "Totalt_budbelopp",
    "accepted_volume": "Tilldelad_volym",
    "isin": "Isin",
    "source_url": "Source_url",
}
